apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: echo-me-ai
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/iebouihi/echo-me-pro.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: echo-me-ai
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
