apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-me-ai
  namespace: echo-me-ai
  labels:
    app: echo-me-ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-me-ai
  template:
    metadata:
      labels:
        app: echo-me-ai
    spec:
      serviceAccountName: echo-me-ai-sa
      containers:
      - name: echo-me-ai
        image: iebouihi/echo-me-pro:1.1.6
        ports:
        - containerPort: 7860
        envFrom:
          - secretRef:
              name: echo-me-ai-secrets
          - configMapRef:
              name: echo-me-ai-config
        readinessProbe:
          httpGet:
            path: /
            port: 7860
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 7860
          initialDelaySeconds: 60
          periodSeconds: 20
        resources:
          requests:
            cpu: "75m"
            memory: "200Mi"
          limits:
            cpu: "250m"
            memory: "300Mi"
        volumeMounts:
          - name: secrets-store-inline
            mountPath: "/mnt/secrets"
            readOnly: true

      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "echo-me-ai-kv-provider"