apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo-me-ai-ingress
  namespace: echo-me-ai
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: demos.imadlabs.co.site
      http:
        paths:
          - path: /ask(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: echo-me-ai-service
                port:
                  number: 80