apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo-me-ai-ingress
  namespace: echo-me-ai
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
spec:
  ingressClassName: nginx
  rules:
    - host: ask.imadlabs.co.site
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: echo-me-ai-service
                port:
                  number: 80