apiVersion: v1
kind: Secret
metadata:
  name: echo-me-ai-secrets
  namespace: echo-me-ai
type: Opaque
stringData:
  OPENAI_API_KEY: "REPLACE_ME"
  PUSHOVER_TOKEN: "REPLACE_ME"
  PUSHOVER_USER: "REPLACE_ME"
  SENDGRID_API_KEY: "REPLACE_ME"