apiVersion: v1
kind: Secret
metadata:
  name: echo-me-ai-secrets
  namespace: echo-me-ai
type: Opaque
stringData:
  OPENAI_API_KEY: "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"
  PUSHOVER_TOKEN: "anmkz6uphncryb2154jnm9v6281aij"
  PUSHOVER_USER: "gffsc5wgnjwzre4k3vzyrqk7q9ayw8"
  SENDGRID_API_KEY: "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"