apiVersion: v1
kind: Service
metadata:
  name: echo-me-ai-service
  namespace: echo-me-ai
spec:
  type: ClusterIP
  selector:
    app: echo-me-ai
  ports:
    - port: 80
      targetPort: 7860